"""Configuration for the AEGIS-R7 graybox v5 craft pass.

V5 is deliberately a surface-craft revision of the accepted v4 feature
layout.  The v4 blend and feature measurements are immutable inputs; every
generated artifact is routed to an isolated ``graybox_v5`` path.
"""

from __future__ import annotations

from copy import deepcopy

from helmet_v4_config import *  # noqa: F401,F403 - protected v4 contract


V4_BLEND_SOURCE = WORK_DIR / "helmet_graybox_v4.blend"
OUTPUT_DIR = BLENDER_DIR / "output" / "graybox_v5"
LOG_DIR = OUTPUT_DIR / "logs"
BLEND_PATH = WORK_DIR / "helmet_graybox_v5.blend"
GLB_PATH = OUTPUT_DIR / "helmet_graybox_v5.glb"
REPORT_PATH = OUTPUT_DIR / "helmet_graybox_v5_report.json"

# Feature locations are frozen at their accepted v4 measurements.  V5 writes
# only a new validation result; it never rewrites the source curves.
FEATURE_CURVES_PATH = BLENDER_DIR / "output" / "graybox_v4" / "feature_curves.json"
FEATURE_VALIDATION_PATH = OUTPUT_DIR / "feature_validation_v5.json"
MEASUREMENTS_PATH = BLENDER_DIR / "output" / "graybox_v3" / "reference_measurements.json"
BASELINE_COMMIT = "17977b0"

# The collection name is retained inside the isolated v5 .blend so the proven
# v4 render/export selection contract remains valid.  It does not imply any
# write to the v3/v4 assets.
HELMET_COLLECTION_NAME = "HELMET_V3"

# Authoritative v4 clean-reimport contract: HelmetRoot plus 54 meshes.
V4_NODE_NAMES = (
    "HelmetRoot",
    "Cheek_L", "Cheek_R", "Chin",
    "CrownFront", "CrownRear",
    "CrownSpine_01", "CrownSpine_02", "CrownSpine_03", "CrownSpine_04",
    "CrownSpine_Cap",
    "EarCover_L", "EarCover_R", "EarEmitter_L", "EarEmitter_R",
    "EarRing_L_Inner", "EarRing_L_Outer", "EarRing_R_Inner", "EarRing_R_Outer",
    "EyeHousing_L", "EyeHousing_R", "EyeLens_L", "EyeLens_R",
    "Faceplate", "FaceplateBezel", "InnerShell",
    "Jaw_L", "Jaw_R", "JawTrim_L", "JawTrim_R", "LowerUTrim",
    "NeckRingFront", "NeckRingRear",
    "RearLayer_L_Lower", "RearLayer_L_Upper",
    "RearLayer_R_Lower", "RearLayer_R_Upper",
    "RearShell_L", "RearShell_R",
    "RearSpine_01", "RearSpine_02", "RearSpine_03", "RearSpine_04",
    "RearSpine_05", "RearSpine_06", "RearSpine_07", "RearSpine_08",
    "RearVent_L_Lower", "RearVent_L_Upper",
    "RearVent_R_Lower", "RearVent_R_Upper",
    "SideGroove_L", "SideGroove_R", "Temple_L", "Temple_R",
)
REQUIRED_EXPORT_PARTS = V4_NODE_NAMES

MATERIALS = deepcopy(MATERIALS)
PART_MATERIALS = deepcopy(PART_MATERIALS)
FIT = deepcopy(FIT)
RENDER = deepcopy(RENDER)
CAMERAS = deepcopy(CAMERAS)
REVIEW_VIEWS = tuple(CAMERAS.keys())
FEATURE_TOLERANCES_PERCENT = deepcopy(FEATURE_TOLERANCES_PERCENT)

# Each iteration starts from the protected v4 blend.  Values therefore encode
# real, monotonic craft improvements instead of cumulative accidental edits.
CRAFT_ITERATIONS = {
    1: {
        "label": "structured faceplate and first real eye-slot cut",
        "facet_depth_scale": 0.86,
        "side_edge_inset_m": 0.0018,
        "eye_housing_recess_m": 0.0008,
        "eye_lens_recess_m": 0.0003,
        "bezel_width_m": 0.0046,
        "mouth_bezel_scale": 0.82,
        "mouth_cover_raise_m": 0.0018,
        "crown_seam_close_m": 0.0028,
        "lower_shell_raise_m": 0.0003,
        "neck_xy_scale": 0.975,
        "neck_raise_m": 0.0035,
        "panel_bevel_m": 0.00048,
        "spine_scale": 0.97,
        "cap_scale": (0.94, 0.84, 0.90),
    },
    2: {
        "label": "deeper eye recess, narrow crown seam and clean lower frame",
        "facet_depth_scale": 0.95,
        "side_edge_inset_m": 0.0032,
        "eye_housing_recess_m": 0.00135,
        "eye_lens_recess_m": 0.00072,
        "bezel_width_m": 0.0039,
        "mouth_bezel_scale": 0.70,
        "mouth_cover_raise_m": 0.0028,
        "crown_seam_close_m": 0.0041,
        "lower_shell_raise_m": 0.00065,
        "neck_xy_scale": 0.958,
        "neck_raise_m": 0.0053,
        "panel_bevel_m": 0.00062,
        "spine_scale": 0.94,
        "cap_scale": (0.88, 0.73, 0.82),
    },
    3: {
        "label": "final machined facets, flush lens, inset base and refined spine",
        "facet_depth_scale": 0.96,
        "side_edge_inset_m": 0.0060,
        "eye_housing_recess_m": 0.0018,
        "eye_lens_recess_m": 0.0010,
        "bezel_width_m": 0.0034,
        "mouth_bezel_scale": 0.60,
        "mouth_cover_raise_m": 0.0050,
        "crown_seam_close_m": 0.0080,
        "lower_shell_raise_m": 0.0010,
        "neck_xy_scale": 0.88,
        "neck_raise_m": 0.0150,
        "panel_bevel_m": 0.00050,
        "spine_scale": 0.92,
        "cap_scale": (0.82, 0.64, 0.75),
    },
    4: {
        "label": "uniform faceplate cage, planar lower armor and fully tucked silhouette",
        "facet_depth_scale": 0.88,
        "side_edge_inset_m": 0.0085,
        "eye_housing_recess_m": 0.0024,
        "eye_lens_recess_m": 0.0019,
        "bezel_width_m": 0.0038,
        "mouth_bezel_scale": 0.66,
        "mouth_cover_raise_m": 0.0090,
        "crown_seam_close_m": 0.0070,
        "lower_shell_raise_m": 0.0015,
        "neck_xy_scale": 0.82,
        "neck_raise_m": 0.0220,
        "panel_bevel_m": 0.00042,
        "spine_scale": 0.93,
        "cap_scale": (1.50, 1.15, 0.80),
    },
    5: {
        "label": "recessed faceplate, compact lower frame and integrated black return lip",
        "facet_depth_scale": 0.72,
        "faceplate_global_offset_m": -0.0065,
        "bezel_projection_offset_m": 0.0120,
        "side_edge_inset_m": 0.0060,
        "eye_housing_recess_m": 0.0025,
        "eye_lens_recess_m": 0.0018,
        "bezel_width_m": 0.0038,
        "mouth_bezel_scale": 0.66,
        "mouth_cover_raise_m": 0.0070,
        "crown_seam_close_m": 0.0070,
        "lower_shell_raise_m": 0.0015,
        "neck_xy_scale": 0.82,
        "neck_raise_m": 0.0220,
        "panel_bevel_m": 0.00038,
        "spine_scale": 0.93,
        "cap_scale": (1.18, 0.90, 0.55),
    },
    6: {
        "label": "explicit topological eye slots and final surface integration",
        "facet_depth_scale": 0.72,
        "faceplate_global_offset_m": -0.0065,
        "bezel_projection_offset_m": 0.0120,
        "side_edge_inset_m": 0.0060,
        "eye_housing_recess_m": 0.0025,
        "eye_lens_recess_m": 0.0018,
        "bezel_width_m": 0.0038,
        "mouth_bezel_scale": 0.66,
        "mouth_cover_raise_m": 0.0070,
        "crown_seam_close_m": 0.0070,
        "lower_shell_raise_m": 0.0015,
        "neck_xy_scale": 0.82,
        "neck_raise_m": 0.0220,
        "panel_bevel_m": 0.00038,
        "spine_scale": 0.93,
        "cap_scale": (1.18, 0.90, 0.55),
    },
    7: {
        "label": "visible recessed faceplate, compact crown cap and clean lower trapezoids",
        "facet_depth_scale": 0.72,
        "faceplate_global_offset_m": -0.0015,
        "bezel_projection_offset_m": 0.0175,
        "side_edge_inset_m": 0.0060,
        "eye_housing_recess_m": 0.0025,
        "eye_lens_recess_m": 0.0018,
        "bezel_width_m": 0.0038,
        "mouth_bezel_scale": 0.66,
        "mouth_cover_raise_m": 0.0070,
        "crown_seam_close_m": 0.0070,
        "lower_shell_raise_m": 0.0015,
        "neck_xy_scale": 0.82,
        "neck_raise_m": 0.0220,
        "panel_bevel_m": 0.00038,
        "spine_scale": 0.93,
        "cap_scale": (1.10, 0.62, 0.55),
    },
    8: {
        "label": "full visible machined skin with narrow closed side guard rails",
        "facet_depth_scale": 0.72,
        "faceplate_global_offset_m": 0.0,
        "bezel_projection_offset_m": 0.0060,
        "side_guard_rails": True,
        "side_edge_inset_m": 0.0060,
        "eye_housing_recess_m": 0.0025,
        "eye_lens_recess_m": 0.0018,
        "bezel_width_m": 0.0038,
        "mouth_bezel_scale": 0.66,
        "mouth_cover_raise_m": 0.0070,
        "crown_seam_close_m": 0.0070,
        "lower_shell_raise_m": 0.0015,
        "neck_xy_scale": 0.82,
        "neck_raise_m": 0.0220,
        "panel_bevel_m": 0.00038,
        "spine_scale": 0.93,
        "cap_scale": (1.10, 0.62, 0.55),
    },
    9: {
        "label": "integrated deep black bezel with no floating side rails",
        "facet_depth_scale": 0.72,
        "faceplate_global_offset_m": 0.0,
        "bezel_projection_offset_m": 0.0320,
        "side_guard_rails": False,
        "side_edge_inset_m": 0.0060,
        "eye_housing_recess_m": 0.0025,
        "eye_lens_recess_m": 0.0018,
        "bezel_width_m": 0.0038,
        "mouth_bezel_scale": 0.66,
        "mouth_cover_raise_m": 0.0070,
        "crown_seam_close_m": 0.0070,
        "lower_shell_raise_m": 0.0015,
        "neck_xy_scale": 0.82,
        "neck_raise_m": 0.0220,
        "panel_bevel_m": 0.00038,
        "spine_scale": 0.93,
        "cap_scale": (1.10, 0.62, 0.55),
    },
    10: {
        "label": "integrated red shell return flanges over a continuous gold machine skin",
        "facet_depth_scale": 0.72,
        "faceplate_global_offset_m": 0.0,
        "bezel_projection_offset_m": 0.0060,
        "side_guard_rails": False,
        "side_edge_inset_m": 0.0060,
        "eye_housing_recess_m": 0.0025,
        "eye_lens_recess_m": 0.0018,
        "bezel_width_m": 0.0038,
        "mouth_bezel_scale": 0.66,
        "mouth_cover_raise_m": 0.0070,
        "crown_seam_close_m": 0.0070,
        "lower_shell_raise_m": 0.0015,
        "neck_xy_scale": 0.82,
        "neck_raise_m": 0.0220,
        "panel_bevel_m": 0.00038,
        "spine_scale": 0.93,
        "cap_scale": (1.10, 0.62, 0.55),
    },
    11: {
        "label": "frozen faceplate XZ boundary with integrated upper and side returns",
        "facet_depth_scale": 0.72,
        "faceplate_global_offset_m": 0.0,
        "bezel_projection_offset_m": 0.0060,
        "side_guard_rails": False,
        "side_edge_inset_m": 0.0060,
        "eye_housing_recess_m": 0.0025,
        "eye_lens_recess_m": 0.0018,
        "bezel_width_m": 0.0038,
        "mouth_bezel_scale": 0.66,
        "mouth_cover_raise_m": 0.0070,
        "crown_seam_close_m": 0.0070,
        "lower_shell_raise_m": 0.0015,
        "neck_xy_scale": 0.82,
        "neck_raise_m": 0.0220,
        "panel_bevel_m": 0.00038,
        "spine_scale": 0.93,
        "cap_scale": (1.10, 0.62, 0.55),
    },
    12: {
        "label": "temple-integrated upper return panels with no displaced bezel",
        "facet_depth_scale": 0.72,
        "faceplate_global_offset_m": 0.0,
        "bezel_projection_offset_m": 0.0060,
        "side_guard_rails": False,
        "side_edge_inset_m": 0.0060,
        "eye_housing_recess_m": 0.0025,
        "eye_lens_recess_m": 0.0018,
        "bezel_width_m": 0.0038,
        "mouth_bezel_scale": 0.66,
        "mouth_cover_raise_m": 0.0070,
        "crown_seam_close_m": 0.0070,
        "lower_shell_raise_m": 0.0015,
        "neck_xy_scale": 0.82,
        "neck_raise_m": 0.0220,
        "panel_bevel_m": 0.00038,
        "spine_scale": 0.93,
        "cap_scale": (1.10, 0.62, 0.55),
    },
    13: {
        "label": "flush tapered temple returns on the accepted v4 face frame",
        "facet_depth_scale": 0.72,
        "faceplate_global_offset_m": 0.0,
        "bezel_projection_offset_m": 0.0060,
        "side_guard_rails": False,
        "side_edge_inset_m": 0.0060,
        "eye_housing_recess_m": 0.0025,
        "eye_lens_recess_m": 0.0018,
        "bezel_width_m": 0.0038,
        "mouth_bezel_scale": 0.66,
        "mouth_cover_raise_m": 0.0070,
        "crown_seam_close_m": 0.0070,
        "lower_shell_raise_m": 0.0015,
        "neck_xy_scale": 0.82,
        "neck_raise_m": 0.0220,
        "panel_bevel_m": 0.00038,
        "spine_scale": 0.93,
        "cap_scale": (1.10, 0.62, 0.55),
    },
    14: {
        "label": "flush two-millimetre center bezel spine over the machined gold skin",
        "facet_depth_scale": 0.72,
        "faceplate_global_offset_m": 0.0,
        "bezel_projection_offset_m": 0.0060,
        "side_guard_rails": False,
        "center_bezel_spine": True,
        "side_edge_inset_m": 0.0060,
        "eye_housing_recess_m": 0.0025,
        "eye_lens_recess_m": 0.0018,
        "bezel_width_m": 0.0038,
        "mouth_bezel_scale": 0.66,
        "mouth_cover_raise_m": 0.0070,
        "crown_seam_close_m": 0.0070,
        "lower_shell_raise_m": 0.0015,
        "neck_xy_scale": 0.82,
        "neck_raise_m": 0.0220,
        "panel_bevel_m": 0.00038,
        "spine_scale": 0.93,
        "cap_scale": (1.10, 0.62, 0.55),
    },
    15: {
        "label": "reference-faithful center ridge, seated lower armor and flush side returns",
        "facet_depth_scale": 0.72,
        "faceplate_global_offset_m": 0.0,
        "bezel_projection_offset_m": 0.0060,
        "side_guard_rails": True,
        "side_guard_forward_m": 0.00035,
        "side_guard_width_m": 0.0022,
        "side_guard_depth_m": 0.0012,
        "center_bezel_spine": False,
        "side_edge_inset_m": 0.0060,
        "eye_housing_recess_m": 0.0025,
        "eye_lens_recess_m": 0.0018,
        "bezel_width_m": 0.0038,
        "mouth_bezel_scale": 0.66,
        "mouth_cover_raise_m": 0.0070,
        "lower_plate_seat_fraction": 0.65,
        "crown_seam_close_m": 0.0095,
        "lower_shell_raise_m": 0.0015,
        "neck_xy_scale": 0.70,
        "neck_raise_m": 0.0300,
        "panel_bevel_m": 0.00038,
        "spine_scale": 0.90,
        "cap_scale": (1.00, 1.05, 0.52),
    },
    16: {
        "label": "concealed side returns, integrated chin prisms and reference-scale spine blocks",
        "facet_depth_scale": 0.72,
        "faceplate_global_offset_m": 0.0,
        "bezel_projection_offset_m": 0.0060,
        "side_guard_rails": True,
        "side_guard_forward_m": 0.00005,
        "side_guard_width_m": 0.0016,
        "side_guard_depth_m": 0.0008,
        "center_bezel_spine": False,
        "side_edge_inset_m": 0.0060,
        "eye_housing_recess_m": 0.0025,
        "eye_lens_recess_m": 0.0018,
        "bezel_width_m": 0.0038,
        "mouth_bezel_scale": 0.66,
        "mouth_cover_raise_m": 0.0070,
        "lower_plate_seat_fraction": 0.35,
        "lower_plate_thickness_m": 0.0016,
        "crown_seam_close_m": 0.0095,
        "lower_shell_raise_m": 0.0015,
        "neck_xy_scale": 0.50,
        "neck_raise_m": 0.0400,
        "panel_bevel_m": 0.00038,
        "spine_scale": 0.90,
        "crown_spine_width_scale": 0.72,
        "crown_spine_bevel_m": 0.0009,
        "cap_scale": (0.55, 1.00, 0.45),
    },
    17: {
        "label": "edge-on side occlusion blades, hidden inner rim and thin seated lower armor",
        "facet_depth_scale": 0.72,
        "faceplate_global_offset_m": 0.0,
        "bezel_projection_offset_m": 0.0060,
        "side_guard_rails": False,
        "side_occlusion_blades": True,
        "side_blade_x_m": 0.075,
        "side_blade_forward_m": 0.00005,
        "side_blade_thickness_m": 0.00055,
        "side_blade_return_depth_m": 0.0022,
        "center_bezel_spine": False,
        "side_edge_inset_m": 0.0060,
        "eye_housing_recess_m": 0.0025,
        "eye_lens_recess_m": 0.0018,
        "bezel_width_m": 0.0038,
        "mouth_bezel_scale": 0.66,
        "mouth_cover_raise_m": 0.0070,
        "lower_plate_seat_fraction": 0.55,
        "lower_plate_thickness_m": 0.0004,
        "crown_seam_close_m": 0.0095,
        "lower_shell_raise_m": 0.0015,
        "neck_xy_scale": 0.50,
        "neck_raise_m": 0.0400,
        "inner_rim_min_z_m": -0.088,
        "panel_bevel_m": 0.00038,
        "spine_scale": 0.90,
        "crown_spine_width_scale": 0.72,
        "crown_spine_bevel_m": 0.0009,
        "cap_scale": (0.78, 1.00, 0.45),
    },
    18: {
        "label": "shell-concealed upper side blades and fully tucked construction rim",
        "facet_depth_scale": 0.72,
        "faceplate_global_offset_m": 0.0,
        "bezel_projection_offset_m": 0.0060,
        "side_guard_rails": False,
        "side_occlusion_blades": True,
        "side_blade_x_m": 0.105,
        "side_blade_v_start": 0.20,
        "side_blade_v_end": 0.54,
        "side_blade_forward_m": 0.00005,
        "side_blade_thickness_m": 0.00008,
        "side_blade_return_depth_m": 0.0018,
        "center_bezel_spine": False,
        "side_edge_inset_m": 0.0060,
        "eye_housing_recess_m": 0.0025,
        "eye_lens_recess_m": 0.0018,
        "bezel_width_m": 0.0038,
        "mouth_bezel_scale": 0.66,
        "mouth_cover_raise_m": 0.0070,
        "lower_plate_seat_fraction": 0.55,
        "lower_plate_thickness_m": 0.00025,
        "crown_seam_close_m": 0.0095,
        "lower_shell_raise_m": 0.0015,
        "neck_xy_scale": 0.30,
        "neck_raise_m": 0.0450,
        "inner_rim_raise_m": 0.035,
        "inner_rim_inset": 0.70,
        "panel_bevel_m": 0.00038,
        "spine_scale": 0.90,
        "crown_spine_width_scale": 0.72,
        "crown_spine_bevel_m": 0.0009,
        "cap_scale": (0.90, 0.85, 0.45),
    },
}

TRIANGLE_LIMIT = 100_000
EXPECTED_NODE_COUNT = 55


def craft_tuning(iteration: int) -> dict:
    """Return an isolated tuning record; later iterations use latest craft."""
    key = min(max(CRAFT_ITERATIONS), max(1, int(iteration)))
    return deepcopy(CRAFT_ITERATIONS[key])


def assert_isolated_paths() -> None:
    protected = {
        (BLENDER_DIR / "output" / "graybox_v3").resolve(),
        (BLENDER_DIR / "output" / "graybox_v4").resolve(),
        (WORK_DIR / "helmet_graybox_v3.blend").resolve(),
        V4_BLEND_SOURCE.resolve(),
    }
    destinations = {OUTPUT_DIR.resolve(), BLEND_PATH.resolve(), GLB_PATH.resolve(), REPORT_PATH.resolve()}
    if protected & destinations:
        raise RuntimeError("v5 output path aliases a protected v3/v4 artifact")
    if OUTPUT_DIR.name != "graybox_v5" or BLEND_PATH.name != "helmet_graybox_v5.blend":
        raise RuntimeError("v5 path isolation contract is invalid")
